### ISSUE TITLE
Support for NitroKey 3A Mini

### ISSUE THREAD

**Issue by vikanezrimaya** [open-keychain/open-keychain#2840]
## Expected Behavior

OKC should use a connected NitroKey 3A Mini as a GPG smartcard to import a PGP key.

## Current Behavior

OKC shows "This Security Token is not yet supported by OpenKeychain"

## Possible Solution

Implement support for NitroKey 3A Mini, I guess?... Shouldn't be too different from a NitroKey 3, since the vendor software (nitropy) recognizes either. Supporting one means supporting both.

## Steps to Reproduce (for bugs)

1. Connect NitroKey 3A Mini via USB
2. Go to OKC -> Manage my keys -> Use Security Token
3. Observe error message (might not always appear — in which case, without closing the app, reconnect the key, go back one screen and try again)

## Context
This NitroKey is seen by `gpg` on my work laptop: 

```console
$ gpg --card-status
Reader ...........: 20A0:42B2:X:0
Application ID ...: D276000124010304000F112C4C680000
Application type .: OpenPGP
Version ..........: 3.4
Manufacturer .....: Nitrokey
Serial number ....: 112C4C68
Name of cardholder: Vika Shleina
Language prefs ...: [not set]
Salutation .......: Ms.
URL of public key : https://github.com/vikanezrimaya.gpg
Login data .......: vika
Signature PIN ....: forced
Key attributes ...: ed25519 cv25519 ed25519
Max. PIN lengths .: 127 127 127
PIN retry counter : 3 0 3
Signature counter : 4
KDF setting ......: off
UIF setting ......: Sign=off Decrypt=off Auth=off
Signature key ....: 5814 50EB 6E17 E715 7C63  E7F1 9879 8C3C 4D68 8D6D
created ....: 2023-07-12 14:52:33
Encryption key....: 1927 B348 1F1E 7F39 0250  399E 8A61 39A9 357C 76FB
created ....: 2023-07-12 14:52:33
Authentication key: ED3E 2C95 B66F 7C35 415D  9F07 3663 330C 2DF9 0D40
created ....: 2023-07-12 14:52:33
General key info..: pub  ed25519/98798C3C4D688D6D 2023-07-12 Vika Shleina <vika@fireburn.ru>
sec>  ed25519/98798C3C4D688D6D  created: 2023-07-12  expires: never
card-no: 000F 112C4C68
ssb>  ed25519/3663330C2DF90D40  created: 2023-07-12  expires: never
card-no: 000F 112C4C68
ssb>  cv25519/8A6139A9357C76FB  created: 2023-07-12  expires: never
card-no: 000F 112C4C68
```
## Your Environment

* Android Version: 12 (2023-01-01 security patch)
* Device Model: Xiaomi A12
* OpenKeychain Version: Various; incl. 5.8.2
* From Google Play or F-Droid?: tried both, same error

**Comment by sjlongland** [comment]
Reproduced the same issue with F-Droid build on a Samsung Active3 tablet and Android 13.

Related discussion: https://support.nitrokey.com/t/support-nitrokey-3-openpgp-on-android-openkeychain/4946/11

Seemingly, the NFC version is supported, but the later firmware removes NFC support for OpenPGP.  Not quite sure what needs to change to make the device "supported", `gnupg` 2.2.41 needed nothing special to support this dongle.

**Comment by Starkstromkonsument** [comment]
Same for Nitrokey 3C NFC (not sure whether there are other differences than the plug)

**Comment by sjlongland** [comment]
@Starkstromkonsument If you could try the branch referenced in #2842 and report back your findings, that would be a big help.  I only have the 3A Mini for testing here.

**Comment by Starkstromkonsument** [comment]
@sjlongland I'm sorry, I don't have any experience with app development and I don't have a suitable build environment set up. At the moment I don't have the time to get into it either. But I could test an apk on my GrapheneOS-Device if anyone is able to provide one.

**Comment by sjlongland** [comment]
@Starkstromkonsument If you trust me (and that's fine if you don't, it pays to be paranoid with this stuff) I did upload a pre-built binary for people to test without setting up a dev environment.

https://github.com/open-keychain/open-keychain/pull/2842#issuecomment-1656555763

As it uses essentially the same identifiers as the Play Store / F-Droid versions, you'll need to uninstall those first before installing this version (otherwise Android will squawk).

**Comment by danielkrajnik** [comment]
@sjlongland Thank you, I will give it a try.

**Comment by danielkrajnik** [comment]
I want to try your build and in terms of being paranoid I'm wondering what's the worst that could happen. Private key stays on Nitrokey and Android sandboxes OKC with the srandard DAC/MAC. I don't know the exact design of OKC and how it interacts with other applications like the password manager for example., so please let me know if there's some attack vector I'm missing.

**Comment by sjlongland** [comment]
Probably the biggest danger, since the private key is not accessible, is disclosure of the pin or cleartext, or unauthorised generation of digital signatures.  i.e. hypothetically that binary if so patched, could call out to a command-and-control server to send cleartexts or receive data to be signed.

**Comment by danielkrajnik** [comment]
Thanks, you'd still need then the Nitrokey or to infect the exact machine with that Nitrokey in some other way to do anything malicious.

**Comment by sjlongland** [comment]
> Thanks, so if the user only accesses Nitrokey's GPG key with a theoretically untrusted OKC, the attacker would still need to get user's physical Nitrokey or infect the exact machine with that Nitrokey in some other way to do anything malicious.

Yeah, it's more a case of that .apk -- if it is itself was manipulated to contain malware (I didn't, but then again, if I was being malicious, I wouldn't admit to doing this anyway), the malware would have the necessary capability to exfiltrate cleartext data decrypted with the private key, or generate hashes.

As @vikanezrimaya has pointed out, a mitigation for this is to configure the NitroKey to require a touch to perform the action.

**Comment by pspoe** [comment]
I have a Nitrokey 3C NFC (USB-C variant) and it works fine with F-Droid open-keychain v6.04 on Android 13 when plugged into the USB-C port of the phone. 

NFC does not work, either because it is not supported or because the power supplied to the Nitrokey via NFC is too weak (is there an easy way to find out which it is?).

**Comment by pjhfggij** [comment]
> NFC does not work, either because it is not supported or because the power supplied to the Nitrokey via NFC is too weak (is there an easy way to find out which it is?).

It's both :) [Developers confirmed it](https://github.com/Nitrokey/nitrokey-3-firmware/issues/270#issuecomment-1568152589) And yes, it's really sad, but I'd rather live in pain than buy a yubikey

**Comment by sjlongland** [comment]
Yep, not a lot I can do about NFC support, as the mini I have does not implement it.

**Comment by pjhfggij** [comment]
Do you know by any chance if there are any plans to provide gpg via NFC for the future models of nitrokey by any chance? It would be really useful.

**Comment by sjlongland** [comment]
> Do you know by any chance if there are any plans to provide gpg via NFC for the future models of nitrokey by any chance? It would be really useful.

I'm not a NitroKey developer, just an end user that wanted to use a NitroKey 3A Mini with Open Keychain.
